export const hotelMutations = {
    SET_USER_HOTELS: 'SET_USER_HOTELS',
    SET_CURRENT_HOTEL: 'SET_CURRENT_HOTEL',
};

export const hotelActions = {
    SET_USER_HOTELS: 'SET_USER_HOTELS',
    CREATE_HOTEL: 'CREATE_HOTEL',
    GET_USER_HOTELS: 'GET_USER_HOTELS',
    GET_BY_ID: 'GET_BY_ID',
    UPDATE_HOTEL: 'UPDATE_HOTEL',
    DELETE_HOTEL: 'DELETE_HOTEL',
    DELETE_ROOM: 'DELETE_ROOM',
    ADD_ROOM: 'ADD_ROOM',
    SET_CURRENT_HOTEL: 'SET_CURRENT_HOTEL',
    UPLOAD_PHOTO: 'UPLOAD_PHOTO',
};
