export const ICONS = {
    home: 'mdi-home',
    signUp: 'mdi-account-plus',
    signIn: 'mdi-login',
    changePassword: 'mdi-lock-reset',
    github: 'mdi-github-circle',
    google: 'mdi-google',
    linkedin: 'mdi-linkedin-box',
    logOut: 'mdi-logout',
    user: 'mdi-account',
    image: 'mdi-image',
    account_edit: 'mdi-account-edit',
    profile: 'mdi-face-profile',
    hotel: 'mdi-hotel',
    add: 'mdi-plus',
    question: 'mdi-help',
};
